baseURL = "https://leviathansystems.github.io/LeviathanDM/"
title = "LeviathanDM Documentation"
languageCode = "en-us"
contentDir = "content/en"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/en"

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango"

[params]
  copyright = "LeviathanDM Contributors"
  github_repo = "https://github.com/LeviathanSystems/LeviathanDM"
  github_branch = "master"
  
  # Version information
  version_menu = "Versions"
  version = "0.0.2"
  url_latest_version = "https://leviathansystems.github.io/LeviathanDM/docs/"
  
  [params.ui]
    sidebar_menu_compact = false
    breadcrumb_disable = false
    sidebar_search_disable = false
    navbar_logo = true
    navbar_translucent_over_cover_disable = false
    
    [params.ui.feedback]
      enable = true
      yes = 'Glad to hear it! Please <a href="https://github.com/LeviathanSystems/LeviathanDM/issues/new">tell us how we can improve</a>.'
      no = 'Sorry to hear that. Please <a href="https://github.com/LeviathanSystems/LeviathanDM/issues/new">tell us how we can improve</a>.'
    
  # Version dropdown configuration
  [[params.versions]]
    version = "latest (development)"
    url = "https://leviathansystems.github.io/LeviathanDM/docs/"
  
  [[params.versions]]
    version = "v0.1.0"
    url = "https://leviathansystems.github.io/LeviathanDM/v0.1.0/"

[menu]
  [[menu.main]]
    name = "Documentation"
    weight = 1
    url = "/docs/"
  [[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/LeviathanSystems/LeviathanDM"
